annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/release-name: fujitsu-fep
apiVersion: v2
appVersion: 1.0.001-ga
description: Helm Chart for Installation of Fujitsu Enterprise Postgres Operator
icon: https://raw.githubusercontent.com/fujitsuaustraliasoftwaretechnology/partner-charts/main-source/assets/logos/fujitsu-fep.png
keywords:
- postgres
- postgresql
- database
- sql
- Fujitsu
- fep
kubeVersion: 1.16 - 1.22
maintainers:
- email: pgtechenquiry@au.fujitsu.com
  name: Fujitsu
  url: https://www.postgresql.fastware.com/
name: fujitsu-fep
type: application
version: 1.0.0
