apiVersion: apps/v1
kind: Deployment
metadata:
   name: fep-ansible-operator-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: fep-ansible-operator
      vendor: Fujitsu
  strategy: {}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        name: fep-ansible-operator
        vendor: Fujitsu
    spec:
      containers:
      - args:
        - --metrics-addr=0.0.0.0:8080
        - --enable-leader-election
        - --leader-election-id=fep-ansible-operator-metrics-exp
        env:
        - name: WATCH_NAMESPACE
          value: '{{ .Release.Namespace }}'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: fep-ansible-operator
        - name: RELATED_IMAGE_FEP
          value: quay.io/fujitsu/fujitsu-enterprise-postgres-13-server:ubi8-13-1.0
        - name: RELATED_IMAGE_BACKUP
          value: quay.io/fujitsu/fujitsu-enterprise-postgres-13-backup:ubi8-13-1.0
        - name: RELATED_IMAGE_RESTORE
          value: quay.io/fujitsu/fujitsu-enterprise-postgres-13-restore:ubi8-13-1.0
        - name: RELATED_IMAGE_PGPOOL2
          value: quay.io/fujitsu/fujitsu-enterprise-postgres-13-pgpool2:ubi8-13-1.0
        - name: RELATED_IMAGE_FEPEXPORTER
          value: quay.io/fujitsu/fujitsu-enterprise-postgres-13-exporter:ubi8-13-1.0
        - name: RELATED_IMAGE_FEPLOGGING
          value: quay.io/fujitsu/fep-fluentd-test:v1.14.0-FEC-162-fluentd-research
        - name: RELATED_IMAGE_FEPLOGGING_FLUENTBIT
          value: quay.io/fujitsu/fep-fluentbit-test:v1.8.4-13dev
        - name: RELATED_IMAGE_CRONJOB
          value: quay.io/fujitsu/fep-cronjob-test:ubi8-FEC-171-cronjob-dev
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: ANSIBLE_DEBUG_LOGS
          value: 'true'
        - name: ANSIBLE_VERBOSITY_FEPCLUSTER_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPCONFIG_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPVOLUME_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPUSER_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPCERT_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPACTION_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPAUTOSCALE_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPEXPORTER_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPLOGGING_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPPGPOOL2_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPBACKUP_FEP_FUJITSU_IO
          value: '4'
        - name: ANSIBLE_VERBOSITY_FEPRESTORE_FEP_FUJITSU_IO
          value: '4'
        image: quay.io/fujitsu/fep-operator-test:v3.1.0-14dev
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 5
        name: fep-ansible-operator
        ports:
        - containerPort: 8080
          name: http
        resources: {}
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
      imagePullSecrets:
      - name: fj-quay-pull-secret
      - name: quay-pull-secret
      serviceAccountName: fep-ansible-operator
      volumes:
      - emptyDir: {}
        name: runner

