{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" -}}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    control-plane: controller-manager
  name: fep-ansible-operator-metrics
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
{{- end -}}
